# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://www.pratermade.com/"
theme = "congo"
defaultContentLanguage = "en"
title = "PRATERMADE"
enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]



[services]
  [services.disqus]
    shortname = '@disqus_pbHha9zlM4'


